driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: debian-7.8
  - name: debian-8.1
  - name: fedora-21
  - name: fedora-22
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: aws::default
  - name: ohai_hint
    run_list: aws::ec2_hints
